# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo This is Job1 - Hello, Kalyan!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      echo Added by Kalyan
    displayName: 'Run a multi-line script'

- job: Job2
  steps:
  - script: echo This is Job2 - Hello, Konda!
    displayName: 'Run a one-line script'
